# Generated by Django 2.2.6 on 2019-11-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfunctions', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.URLField(default='https://minify.tech/general/'),
        ),
    ]
