# Generated by Django 2.2.5 on 2019-09-25 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='base.QuestionTags')),
            ],
        ),
        migrations.CreateModel(
            name='PNotes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('NOTE', 'Note'), ('ERRORS', 'Errors'), ('TEMPLATES', 'Templates'), ('PROCEDURES', 'Procedures')], default='NOTE', max_length=11)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('resource_linkA', models.URLField(blank=True, max_length=1500)),
                ('resource_linkB', models.URLField(blank=True, max_length=1500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
