# Generated by Django 2.2.5 on 2019-09-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pnotes',
            options={'verbose_name': 'P-Note', 'verbose_name_plural': 'P-Notes'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questiontags',
            options={'verbose_name': 'Question tag', 'verbose_name_plural': 'Question tags'},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
    ]
