# Generated by Django 2.2.6 on 2019-10-08 17:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
