# Generated by Django 2.2.6 on 2019-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20191010_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
