# Generated by Django 2.2.6 on 2019-10-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20191011_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queanswercomment',
            options={'verbose_name': 'Question-answer Comment', 'verbose_name_plural': 'Question-answer Comments'},
        )
    ]
