# Generated by Django 2.2.6 on 2019-10-19 22:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20191019_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='users_vote',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
