# Generated by Django 2.2.6 on 2019-10-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20191024_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='acctmang.Profile'),
        ),
    ]
