# Generated by Django 2.2.6 on 2019-10-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0004_auto_20191025_1227'),
        ('base', '0018_auto_20191028_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsCommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctmang.Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcommentary', to='base.Posts')),
            ],
            options={
                'verbose_name': 'Post-Comment',
                'verbose_name_plural': 'Post-Comments',
            },
        ),
    ]
