# Generated by Django 2.2.6 on 2019-11-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20191101_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='links',
            field=models.CharField(max_length=2000),
        ),
    ]
