# Generated by Django 2.2.6 on 2019-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20191101_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
