# Generated by Django 2.2.6 on 2019-11-05 16:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_questions_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='permitted_viewers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
