# Generated by Django 2.2.6 on 2019-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='ancladmin', unique=True),
            preserve_default=False,
        ),
    ]
