# Generated by Django 2.2.6 on 2019-11-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0006_profile_tstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
